name: Deploy Cloud Function

on:
  push:
    branches:
      - main  # Adjust to your main branch name.

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CURRENT_BUCKET: pizza_code_bucket
      SDK_TYPE: ${{ secrets.SDK_TYPE }}
      SDK_PROJECT_ID: ${{ secrets.SDK_PROJECT_ID }}
      SDK_PRIVATE_KEY_ID: ${{ secrets.SDK_PRIVATE_KEY_ID }}
      SDK_PRIVATE_KEY: ${{ secrets.SDK_PRIVATE_KEY }}
      SDK_CLIENT_EMAIL: ${{ secrets.SDK_CLIENT_EMAIL }}
      SDK_CLIENT_ID: ${{ secrets.SDK_CLIENT_ID }}
      SDK_CLIENT_X509_CERT_URL: ${{ secrets.SDK_CLIENT_X509_CERT_URL }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_USERNAME: ${{ secrets.FIREBASE_USERNAME }}
      FIREBASE_PASSWORD: ${{ secrets.FIREBASE_PASSWORD }}
      SEND_GMAIL_USERNAME: ${{ secrets.SEND_GMAIL_USERNAME }}
      SEND_GMAIL_APP_PASSWORD: ${{ secrets.SEND_GMAIL_APP_PASSWORD }}
      TEST_SECRET: ${{ secrets.TEST_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Set .env vars for Cloud Run deployment
        run: |# Create an array with all the environment variable assignments
          ENV_VARS_ARRAY=(
            "SDK_TYPE=${SDK_TYPE}"
            "SDK_PROJECT_ID=${SDK_PROJECT_ID}"
            "SDK_PRIVATE_KEY=${SDK_PRIVATE_KEY}"
            "SDK_PRIVATE_KEY_ID=${SDK_PRIVATE_KEY_ID}"
            "SDK_CLIENT_EMAIL=${SDK_CLIENT_EMAIL}"
            "SDK_CLIENT_ID=${SDK_CLIENT_ID}"
            "SDK_CLIENT_X509_CERT_URL=${SDK_CLIENT_X509_CERT_URL}"
            "FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}"
            "FIREBASE_API_KEY=${FIREBASE_API_KEY}"
            "FIREBASE_USERNAME=${FIREBASE_USERNAME}"
            "FIREBASE_PASSWORD=${FIREBASE_PASSWORD}"
            "SEND_GMAIL_APP_PASSWORD=${SEND_GMAIL_APP_PASSWORD}"
            "SEND_GMAIL_USERNAME=${SEND_GMAIL_USERNAME}"
          )

           # Join the array elements into a comma-separated string
          UPDATE_ENV_VARS_ARG=$(IFS=,; echo "${ENV_VARS_ARRAY[*]}")
          echo "UPDATE_ENV_VARS_ARG=$UPDATE_ENV_VARS_ARG" >> $GITHUB_ENV
          CURRENT_BUCKET=pizza_code_bucket
          echo "CURRENT_BUCKET=$CURRENT_BUCKET" >> $GITHUB_ENV

      - name: Deploy conversation_handler Cloud Function
        run: |
          echo "Deploying with env vars: $UPDATE_ENV_VARS_ARG"
          gcloud functions deploy conversation_handler \
            --source=. \
            --runtime=python39 \
            --entry-point=conversation_handler \
            --memory 128MB \
            --trigger-http \
            --allow-unauthenticated \
            --stage-bucket=$CURRENT_BUCKET \
            --update-env-vars=$UPDATE_ENV_VARS_ARG

      - name: Deploy order_handler Cloud Function
        run: |
          echo "Deploying with env vars: $UPDATE_ENV_VARS_ARG"
          gcloud functions deploy order_handler \
            --source=. \
            --runtime=python39 \
            --entry-point=order_handler \
            --memory 128MB \
            --trigger-http \
            --allow-unauthenticated \
            --stage-bucket=$CURRENT_BUCKET \
            --update-env-vars=$UPDATE_ENV_VARS_ARG

      - name: Deploy user_handler Cloud Function
        run: |
          echo "Deploying with env vars: $UPDATE_ENV_VARS_ARG"
          gcloud functions deploy user_handler \
            --source=. \
            --runtime=python39 \
            --entry-point=user_handler \
            --memory 128MB \
            --trigger-http \
            --allow-unauthenticated \
            --stage-bucket=$CURRENT_BUCKET \
            --update-env-vars=$UPDATE_ENV_VARS_ARG

#      - name: Deploy budget_alert Cloud Function
#        run: |
#          echo "Deploying with env vars: $UPDATE_ENV_VARS_ARG"
#          gcloud functions deploy budget_alert_endpoint \
#            --source=. \
#            --runtime=python39 \
#            --entry-point=budget_alert_endpoint \
#            --memory 128MB \
#            --trigger-http \
#            --allow-unauthenticated \
#            --update-env-vars $UPDATE_ENV_VARS_ARG \
#            --stage-bucket=firebase_code_bucket